# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md", "_drafts/template.md"] # files to exclude
highlighter: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: L'actualité PostgreSQL par DALIBO 

title: L'actualité PostgreSQL par DALIBO
description: DALIBO est le spécialiste français de PostgreSQL. Nous proposons du support, de la formation et du conseil depuis 2005.
author:
  name: DALIBO
  email: contact@dalibo.com
  github: dalibo
  twitter: dalibo
  pinterest: 
  linkedin: 
  bio: DALIBO est le spécialiste français de PostgreSQL. Nous proposons du support, de la formation et du conseil depuis 2005.

rss_path: feed.xml
tags_path: tags.html

ga_id: UA-637331-11

BASE_PATH: http://blog.dalibo.com
